# Use the latest LTS version of Node.js
FROM node:18-alpine

#Set the working directory inside the container
WORKDIR /server

# Copy the package.json and package-lock.json files to the container  
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container    
COPY . .

# Expose the port your app runs on  
EXPOSE 8080

# Define the command to run your app
CMD ["npm","start"]